// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgpesysiqpjuxccbowho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtncGVzeXNpcXBqdXhjY2Jvd2hvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyOTEzNzksImV4cCI6MjA2ODg2NzM3OX0.SIrT5T5C-1h2Hupa-Phyxa_PHuD3XDl08rBvfFIeNRQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});