import React, { useState } from 'react';
import { 
  FileText, 
  Plus, 
  Download, 
  Upload, 
  Search, 
  Filter, 
  Eye, 
  Edit, 
  Trash2, 
  Send, 
  Clock, 
  CheckCircle, 
  XCircle, 
  QrCode,
  Shield,
  Archive,
  FileSignature,
  Mail,
  Calendar,
  User,
  BookOpen,
  Award
} from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';

const AdminDocumentsOF = () => {
  const [searchTerm, setSearchTerm] = useState('');
  const [filterType, setFilterType] = useState('all');
  const [filterStatus, setFilterStatus] = useState('all');
  const [filterFormation, setFilterFormation] = useState('all');
  const [showUploadDialog, setShowUploadDialog] = useState(false);
  const [selectedDocument, setSelectedDocument] = useState<any>(null);

  // Documents générés automatiquement
  const generatedDocuments = [
    {
      id: '1',
      type: 'attestation',
      title: 'Attestation de fin de formation - Marie Dupont',
      formation: 'React Avancé',
      apprenant: 'Marie Dupont',
      status: 'sent',
      sentDate: '2024-01-15T10:30:00Z',
      readDate: '2024-01-15T11:45:00Z',
      signedDate: null,
      qrCode: 'QR123456',
      uniqueCode: 'ATT-2024-001',
      fileUrl: '/docs/attestation-marie-dupont.pdf',
      autoGenerated: true
    },
    {
      id: '2',
      type: 'certificat',
      title: 'Certificat de réalisation - Jean Martin',
      formation: 'JavaScript ES6',
      apprenant: 'Jean Martin',
      status: 'signed',
      sentDate: '2024-01-14T14:20:00Z',
      readDate: '2024-01-14T15:30:00Z',
      signedDate: '2024-01-14T16:45:00Z',
      qrCode: 'QR789012',
      uniqueCode: 'CERT-2024-002',
      fileUrl: '/docs/certificat-jean-martin.pdf',
      autoGenerated: true
    },
    {
      id: '3',
      type: 'emargement',
      title: 'Feuille d\'émargement - Session 1',
      formation: 'Angular Débutant',
      apprenant: 'Tous',
      status: 'pending',
      sentDate: null,
      readDate: null,
      signedDate: null,
      qrCode: 'QR345678',
      uniqueCode: 'EMARG-2024-003',
      fileUrl: '/docs/emargement-session1.pdf',
      autoGenerated: true
    },
    {
      id: '4',
      type: 'convention',
      title: 'Convention de formation - Sophie Bernard',
      formation: 'Vue.js',
      apprenant: 'Sophie Bernard',
      status: 'signed',
      sentDate: '2024-01-12T09:15:00Z',
      readDate: '2024-01-12T10:30:00Z',
      signedDate: '2024-01-12T11:20:00Z',
      qrCode: 'QR901234',
      uniqueCode: 'CONV-2024-004',
      fileUrl: '/docs/convention-sophie-bernard.pdf',
      autoGenerated: true
    }
  ];

  // Documents déposés par l'OF
  const uploadedDocuments = [
    {
      id: '5',
      type: 'template',
      title: 'Convention type - Template',
      category: 'Convention-type',
      uploadDate: '2024-01-10T14:00:00Z',
      fileUrl: '/docs/convention-template.pdf',
      autoGenerated: false,
      usedInFormations: ['React Avancé', 'Vue.js']
    },
    {
      id: '6',
      type: 'reglement',
      title: 'Règlement intérieur OF',
      category: 'Règlement intérieur',
      uploadDate: '2024-01-08T16:30:00Z',
      fileUrl: '/docs/reglement-interieur.pdf',
      autoGenerated: false,
      usedInFormations: ['Toutes']
    },
    {
      id: '7',
      type: 'ressource',
      title: 'Guide d\'évaluation React',
      category: 'Grilles d\'évaluation',
      uploadDate: '2024-01-05T11:20:00Z',
      fileUrl: '/docs/guide-evaluation-react.pdf',
      autoGenerated: false,
      usedInFormations: ['React Avancé']
    }
  ];

  // Historique des envois
  const sendHistory = [
    {
      id: '1',
      documentId: '1',
      documentTitle: 'Attestation de fin de formation',
      recipient: 'marie.dupont@email.com',
      recipientName: 'Marie Dupont',
      sentDate: '2024-01-15T10:30:00Z',
      status: 'delivered',
      readDate: '2024-01-15T11:45:00Z',
      proofUrl: '/proofs/envoi-001.pdf'
    },
    {
      id: '2',
      documentId: '4',
      documentTitle: 'Convention de formation',
      recipient: 'sophie.bernard@email.com',
      recipientName: 'Sophie Bernard',
      sentDate: '2024-01-12T09:15:00Z',
      status: 'signed',
      readDate: '2024-01-12T10:30:00Z',
      signedDate: '2024-01-12T11:20:00Z',
      proofUrl: '/proofs/envoi-004.pdf'
    }
  ];

  const documentTypes = [
    { value: 'attestation', label: 'Attestation', icon: FileText },
    { value: 'certificat', label: 'Certificat', icon: Award },
    { value: 'emargement', label: 'Émargement', icon: FileSignature },
    { value: 'convention', label: 'Convention', icon: FileText },
    { value: 'logs', label: 'Logs de connexion', icon: Shield },
    { value: 'planning', label: 'Planning', icon: Calendar },
    { value: 'evaluation', label: 'Évaluation', icon: BookOpen }
  ];

  const getStatusBadge = (status: string) => {
    const statusConfig = {
      sent: { variant: 'default' as const, label: 'Envoyé', icon: Mail },
      delivered: { variant: 'default' as const, label: 'Livré', icon: CheckCircle },
      read: { variant: 'secondary' as const, label: 'Lu', icon: Eye },
      signed: { variant: 'default' as const, label: 'Signé', icon: FileSignature },
      pending: { variant: 'outline' as const, label: 'En attente', icon: Clock },
      failed: { variant: 'destructive' as const, label: 'Échec', icon: XCircle }
    };
    
    const config = statusConfig[status as keyof typeof statusConfig] || { variant: 'outline' as const, label: status, icon: Clock };
    const Icon = config.icon;
    
    return (
      <Badge variant={config.variant} className="flex items-center gap-1">
        <Icon className="h-3 w-3" />
        {config.label}
      </Badge>
    );
  };

  const getDocumentTypeBadge = (type: string) => {
    const colors = {
      'attestation': 'bg-blue-500',
      'certificat': 'bg-green-500',
      'emargement': 'bg-orange-500',
      'convention': 'bg-purple-500',
      'logs': 'bg-red-500',
      'planning': 'bg-yellow-500',
      'evaluation': 'bg-teal-500',
      'template': 'bg-gray-500',
      'reglement': 'bg-indigo-500',
      'ressource': 'bg-pink-500'
    };
    
    return (
      <Badge className={`${colors[type as keyof typeof colors] || 'bg-gray-500'} text-white`}>
        {type}
      </Badge>
    );
  };

  const filteredGeneratedDocuments = generatedDocuments.filter(doc => {
    const matchesSearch = doc.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         doc.apprenant.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesType = filterType === 'all' || doc.type === filterType;
    const matchesStatus = filterStatus === 'all' || doc.status === filterStatus;
    const matchesFormation = filterFormation === 'all' || doc.formation === filterFormation;
    
    return matchesSearch && matchesType && matchesStatus && matchesFormation;
  });

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-gray-900 mb-2">Gestion des Documents OF</h1>
          <p className="text-gray-600">Génération automatique, bibliothèque OF et suivi des envois</p>
        </div>
        <div className="flex gap-2">
          <Dialog open={showUploadDialog} onOpenChange={setShowUploadDialog}>
            <DialogTrigger asChild>
              <Button variant="outline">
                <Upload className="w-4 h-4 mr-2" />
                Déposer un document
              </Button>
            </DialogTrigger>
            <DialogContent>
              <DialogHeader>
                <DialogTitle>Déposer un document</DialogTitle>
                <DialogDescription>
                  Ajoutez un document à votre bibliothèque OF
                </DialogDescription>
              </DialogHeader>
              <div className="space-y-4">
                <div>
                  <Label htmlFor="category">Catégorie</Label>
                  <Select>
                    <SelectTrigger>
                      <SelectValue placeholder="Sélectionnez une catégorie" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="convention-type">Convention-type</SelectItem>
                      <SelectItem value="fiche-inscription">Fiche d'inscription</SelectItem>
                      <SelectItem value="reglement">Règlement intérieur</SelectItem>
                      <SelectItem value="planning">Planning de sessions</SelectItem>
                      <SelectItem value="evaluation">Grilles d'évaluation</SelectItem>
                      <SelectItem value="ressource">Ressources pédagogiques</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div>
                  <Label htmlFor="title">Titre du document</Label>
                  <Input id="title" placeholder="Ex: Convention type React" />
                </div>
                <div>
                  <Label htmlFor="file">Fichier</Label>
                  <div className="border-2 border-dashed border-gray-300 rounded-lg p-6 text-center">
                    <Upload className="w-8 h-8 text-gray-400 mx-auto mb-2" />
                    <p className="text-sm text-gray-600">Glissez-déposez un fichier ou cliquez pour sélectionner</p>
                  </div>
                </div>
                <div className="flex justify-end space-x-2">
                  <Button variant="outline" onClick={() => setShowUploadDialog(false)}>
                    Annuler
                  </Button>
                  <Button onClick={() => setShowUploadDialog(false)}>
                    Déposer
                  </Button>
                </div>
              </div>
            </DialogContent>
          </Dialog>
          <Button>
            <Plus className="w-4 h-4 mr-2" />
            Générer document
          </Button>
        </div>
      </div>

      {/* Statistiques */}
      <div className="grid md:grid-cols-4 gap-4">
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center space-x-3">
              <FileText className="w-8 h-8 text-blue-500" />
              <div>
                <p className="text-2xl font-bold">{generatedDocuments.length}</p>
                <p className="text-sm text-gray-600">Documents générés</p>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center space-x-3">
              <FileSignature className="w-8 h-8 text-green-500" />
              <div>
                <p className="text-2xl font-bold">
                  {generatedDocuments.filter(d => d.status === 'signed').length}
                </p>
                <p className="text-sm text-gray-600">Documents signés</p>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center space-x-3">
              <Archive className="w-8 h-8 text-purple-500" />
              <div>
                <p className="text-2xl font-bold">{uploadedDocuments.length}</p>
                <p className="text-sm text-gray-600">Bibliothèque OF</p>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center space-x-3">
              <Mail className="w-8 h-8 text-orange-500" />
              <div>
                <p className="text-2xl font-bold">{sendHistory.length}</p>
                <p className="text-sm text-gray-600">Envois ce mois</p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      <Tabs defaultValue="generated" className="space-y-6">
        <TabsList className="grid w-full grid-cols-4">
          <TabsTrigger value="generated">Documents générés</TabsTrigger>
          <TabsTrigger value="library">Bibliothèque OF</TabsTrigger>
          <TabsTrigger value="sending">Suivi des envois</TabsTrigger>
          <TabsTrigger value="automation">Automatisation</TabsTrigger>
        </TabsList>

        {/* Documents générés automatiquement */}
        <TabsContent value="generated">
          <Card>
            <CardHeader>
              <CardTitle>Documents générés automatiquement</CardTitle>
              <CardDescription>
                Attestations, certificats, émargements et autres documents générés par la plateforme
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="flex items-center space-x-4 mb-4">
                <div className="relative flex-1">
                  <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 h-4 w-4" />
                  <Input
                    placeholder="Rechercher par titre, apprenant..."
                    value={searchTerm}
                    onChange={(e) => setSearchTerm(e.target.value)}
                    className="pl-10"
                  />
                </div>
                <Select value={filterType} onValueChange={setFilterType}>
                  <SelectTrigger className="w-40">
                    <SelectValue placeholder="Type" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">Tous types</SelectItem>
                    <SelectItem value="attestation">Attestation</SelectItem>
                    <SelectItem value="certificat">Certificat</SelectItem>
                    <SelectItem value="emargement">Émargement</SelectItem>
                    <SelectItem value="convention">Convention</SelectItem>
                  </SelectContent>
                </Select>
                <Select value={filterStatus} onValueChange={setFilterStatus}>
                  <SelectTrigger className="w-40">
                    <SelectValue placeholder="Statut" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">Tous statuts</SelectItem>
                    <SelectItem value="sent">Envoyé</SelectItem>
                    <SelectItem value="read">Lu</SelectItem>
                    <SelectItem value="signed">Signé</SelectItem>
                    <SelectItem value="pending">En attente</SelectItem>
                  </SelectContent>
                </Select>
                <Select value={filterFormation} onValueChange={setFilterFormation}>
                  <SelectTrigger className="w-40">
                    <SelectValue placeholder="Formation" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">Toutes</SelectItem>
                    <SelectItem value="React Avancé">React Avancé</SelectItem>
                    <SelectItem value="Vue.js">Vue.js</SelectItem>
                    <SelectItem value="Angular Débutant">Angular Débutant</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Type</TableHead>
                    <TableHead>Document</TableHead>
                    <TableHead>Formation</TableHead>
                    <TableHead>Apprenant</TableHead>
                    <TableHead>Statut</TableHead>
                    <TableHead>Code unique</TableHead>
                    <TableHead>Actions</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {filteredGeneratedDocuments.map((doc) => (
                    <TableRow key={doc.id}>
                      <TableCell>{getDocumentTypeBadge(doc.type)}</TableCell>
                      <TableCell>
                        <div className="flex items-center space-x-2">
                          <span className="font-medium">{doc.title}</span>
                          {doc.qrCode && (
                            <QrCode className="h-4 w-4 text-gray-500" />
                          )}
                        </div>
                      </TableCell>
                      <TableCell>{doc.formation}</TableCell>
                      <TableCell>{doc.apprenant}</TableCell>
                      <TableCell>{getStatusBadge(doc.status)}</TableCell>
                      <TableCell>
                        <span className="font-mono text-sm">{doc.uniqueCode}</span>
                      </TableCell>
                      <TableCell>
                        <div className="flex space-x-2">
                          <Button size="sm" variant="outline" title="Prévisualiser">
                            <Eye className="w-4 h-4" />
                          </Button>
                          <Button size="sm" variant="outline" title="Télécharger">
                            <Download className="w-4 h-4" />
                          </Button>
                          <Button size="sm" variant="outline" title="Renvoyer">
                            <Send className="w-4 h-4" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </TabsContent>

        {/* Bibliothèque OF */}
        <TabsContent value="library">
          <Card>
            <CardHeader>
              <CardTitle>Bibliothèque OF</CardTitle>
              <CardDescription>
                Documents déposés par l'organisme de formation (templates, ressources, etc.)
              </CardDescription>
            </CardHeader>
            <CardContent>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Type</TableHead>
                    <TableHead>Document</TableHead>
                    <TableHead>Catégorie</TableHead>
                    <TableHead>Utilisé dans</TableHead>
                    <TableHead>Date d'ajout</TableHead>
                    <TableHead>Actions</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {uploadedDocuments.map((doc) => (
                    <TableRow key={doc.id}>
                      <TableCell>{getDocumentTypeBadge(doc.type)}</TableCell>
                      <TableCell className="font-medium">{doc.title}</TableCell>
                      <TableCell>{doc.category}</TableCell>
                      <TableCell>
                        <div className="flex flex-wrap gap-1">
                          {doc.usedInFormations.map((formation, index) => (
                            <Badge key={index} variant="outline" className="text-xs">
                              {formation}
                            </Badge>
                          ))}
                        </div>
                      </TableCell>
                      <TableCell>
                        {new Date(doc.uploadDate).toLocaleDateString('fr-FR')}
                      </TableCell>
                      <TableCell>
                        <div className="flex space-x-2">
                          <Button size="sm" variant="outline">
                            <Eye className="w-4 h-4" />
                          </Button>
                          <Button size="sm" variant="outline">
                            <Download className="w-4 h-4" />
                          </Button>
                          <Button size="sm" variant="outline">
                            <Edit className="w-4 h-4" />
                          </Button>
                          <Button size="sm" variant="outline">
                            <Trash2 className="w-4 h-4" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </TabsContent>

        {/* Suivi des envois */}
        <TabsContent value="sending">
          <Card>
            <CardHeader>
              <CardTitle>Historique des envois</CardTitle>
              <CardDescription>
                Suivi détaillé de tous les envois de documents avec preuves
              </CardDescription>
            </CardHeader>
            <CardContent>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Document</TableHead>
                    <TableHead>Destinataire</TableHead>
                    <TableHead>Date d'envoi</TableHead>
                    <TableHead>Statut</TableHead>
                    <TableHead>Date de lecture</TableHead>
                    <TableHead>Actions</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {sendHistory.map((send) => (
                    <TableRow key={send.id}>
                      <TableCell className="font-medium">{send.documentTitle}</TableCell>
                      <TableCell>
                        <div>
                          <div className="font-medium">{send.recipientName}</div>
                          <div className="text-sm text-gray-500">{send.recipient}</div>
                        </div>
                      </TableCell>
                      <TableCell>
                        {new Date(send.sentDate).toLocaleString('fr-FR')}
                      </TableCell>
                      <TableCell>{getStatusBadge(send.status)}</TableCell>
                      <TableCell>
                        {send.readDate ? new Date(send.readDate).toLocaleString('fr-FR') : '-'}
                      </TableCell>
                      <TableCell>
                        <div className="flex space-x-2">
                          <Button size="sm" variant="outline" title="Preuve d'envoi">
                            <Shield className="w-4 h-4" />
                          </Button>
                          <Button size="sm" variant="outline" title="Renvoyer">
                            <Send className="w-4 h-4" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </TabsContent>

        {/* Automatisation */}
        <TabsContent value="automation">
          <div className="space-y-6">
            <Card>
              <CardHeader>
                <CardTitle>Règles d'automatisation</CardTitle>
                <CardDescription>
                  Configuration des envois automatiques de documents
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
                    <h4 className="font-medium mb-2">Envois automatiques activés :</h4>
                    <div className="space-y-2 text-sm">
                      <div className="flex items-center justify-between">
                        <span>• À l'inscription (fiche + convocation + règlement)</span>
                        <Badge variant="default">Actif</Badge>
                      </div>
                      <div className="flex items-center justify-between">
                        <span>• À la fin de formation (attestation + certificat)</span>
                        <Badge variant="default">Actif</Badge>
                      </div>
                      <div className="flex items-center justify-between">
                        <span>• Relances automatiques (émargement manquant)</span>
                        <Badge variant="default">Actif</Badge>
                      </div>
                    </div>
                  </div>
                  
                  <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4">
                    <h4 className="font-medium mb-2">Envois programmés :</h4>
                    <div className="space-y-2 text-sm">
                      <div className="flex items-center justify-between">
                        <span>• Convocation 48h avant début formation</span>
                        <Badge variant="outline">Programmé</Badge>
                      </div>
                      <div className="flex items-center justify-between">
                        <span>• Rappel évaluation finale J-2</span>
                        <Badge variant="outline">Programmé</Badge>
                      </div>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>Sécurité et traçabilité</CardTitle>
                <CardDescription>
                  Système de sécurisation et de traçabilité des documents
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="grid md:grid-cols-2 gap-4">
                  <div className="bg-green-50 border border-green-200 rounded-lg p-4">
                    <h4 className="font-medium mb-2 flex items-center">
                      <QrCode className="w-5 h-5 mr-2" />
                      QR Code & Traçabilité
                    </h4>
                    <div className="text-sm space-y-1">
                      <p>• QR code unique sur chaque document</p>
                      <p>• Code alphanumérique de traçabilité</p>
                      <p>• Vérification en ligne possible</p>
                    </div>
                  </div>
                  
                  <div className="bg-purple-50 border border-purple-200 rounded-lg p-4">
                    <h4 className="font-medium mb-2 flex items-center">
                      <Shield className="w-5 h-5 mr-2" />
                      Sécurité & Archivage
                    </h4>
                    <div className="text-sm space-y-1">
                      <p>• Documents non modifiables après génération</p>
                      <p>• Archivage sécurisé avec horodatage</p>
                      <p>• Preuve de signature électronique</p>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        </TabsContent>
      </Tabs>
    </div>
  );
};

export default AdminDocumentsOF;
